exports.form1=[
    {
        label:'Name',
        type:'text',
        name:'name'
    },
    {
        label:'Phone',
        type:'tel',
        name:'phone'
    },
]
exports.form2=[
    {
        label:'Email',
        type:'email',
        name:'email'
    },
    {
        label:'Address',
        type:'text',
        name:'address'
    },
]
exports.form3=[
    {
        label:'Pin',
        type:'number',
        name:'pin'
    },
    {
        label:'Aadhar Card',
        type:'number',
        name:'aadhar'
    },
]
exports.form4=[
    {
        label:'Pan Card',
        type:'number',
        name:'pan'
    },
    {
        label:'Message',
        type:'text',
        name:'message'
    },
]